# 왜 선형대수를 알아야 하는가

 ## Deep learning 을 이해하기 위해서는 선형대수+행렬미분+확률의 탄탄한 기초가 필요하다
 
 ## 목표: 선형대수와 행렬미분의 기초를 배우고 간단한 머신러닝 알고리즘을 유도해보자

.

**python에서의 벡터, 행렬 표현방법**

In [1]:
[10.5, 5.2, 3.25, 7.0]

[10.5, 5.2, 3.25, 7.0]

In [2]:
import numpy as np
x = np.array([10.5,5.2,3.25])

In [3]:
x.shape

(3,)

In [4]:
x[2]

3.25

In [5]:
np.expand_dims(x, axis=1).shape # 열 추가
# expand_dims: 차원 추가


(3, 1)

In [6]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x.dot(y)

32

In [7]:
y.dot(x) #벡터 곱 교환법칙 성립

32

In [8]:
x = np.expand_dims(x, axis=1) # 행렬로 만들어주기 (열 추가)
y = np.expand_dims(y, axis=0) # 행렬로 만들어주기 (행 추가)
x.shape, y.shape

((3, 1), (1, 3))

In [9]:
np.matmul(x,y) # 행렬의 곱에서는 일반적으로 matmul을 사용

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [10]:
ones = np.ones([1,4]) # 원소들이 모두 1
ones

array([[1., 1., 1., 1.]])

In [11]:
np.diag([4,5,6]) # 대각행렬 만들기

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

diag 함수에 행렬을 전달하면 주대각선 값들을 얻을 수 있음

In [12]:
D = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])
np.diag(D) # 주대각선 값들을 얻을 수 있음

array([1, 5, 9])

eye함수를 사용하면 원하는 크기의 단위행렬 생성 가능

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

넘파이의 T속성을 사용해서 전치행렬을 구할 수 있음.

In [14]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [15]:
A.T #Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
A.T.T # 원래의 행렬

array([[1, 2, 3],
       [4, 5, 6]])

행렬의 대각합은 np.trace(행렬이름) 으로 구할 수 있음

In [17]:
A = np.array([
    [100,200,300],
    [10,20,30],
    [1,2,3],
])
np.trace(A)

123

벡터의 norm 

In [19]:
import numpy.linalg as LA # 선형수학 불러오기
LA.norm(np.array([3,4])) # 선형수학의 norm사용

5.0

벡터의 rank

In [21]:
LA.matrix_rank(A) # matrix_rank() 함수는 배열의 행렬 순위를 반환한다

1

numpy.linalg 모듈의 det함수를 사용하면 행렬식을 쉽게 구할 수 있다

In [22]:
LA.det(A) #linalg을 LA로 import 해온 상태

2.5658541216885238e-46

In [23]:
eigenvalues, eigenvectors = LA.eig(A) #eig 함수: 고유값과 고유벡터를 반환함
eigenvalues, eigenvectors

(array([1.23000000e+02, 1.04073179e-14, 1.69021067e-16]),
 array([[ 0.99498793, -0.89862233, -0.24632167],
        [ 0.09949879,  0.43866564, -0.76651171],
        [ 0.00994988,  0.00709702,  0.59311503]]))